<a href="https://colab.research.google.com/github/armandoordonez/eda_couse/blob/main/Basic_Estimators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from sklearn.base import TransformerMixin
from sklearn.base import BaseEstimator
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline


class MyOwnTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X

myot = MyOwnTransformer()

In [ ]:
X, y = load_iris(return_X_y=True)
myot.transform(X) 

In [14]:

pipe = make_pipeline(MyOwnTransformer(), LogisticRegression(random_state=10, solver='lbfgs',max_iter=1000))
 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
pipe.predict(X)  


In [16]:
from sklearn.base import TransformerMixin
from sklearn.base import BaseEstimator
from sklearn.base import RegressorMixin
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

import numpy as np

class MyOwnRegressor(BaseEstimator, RegressorMixin):
    def fit(self, X, y):
        return self
    def predict(self, X):
        return np.mean(X, axis=1)

In [17]:
from sklearn.datasets import load_diabetes


X, y = load_diabetes(return_X_y=True)

pipe = make_pipeline(MyOwnTransformer(), MyOwnRegressor())
pipe.fit(X, y)  


Pipeline(steps=[('myowntransformer', MyOwnTransformer()),
                ('myownregressor', MyOwnRegressor())])

In [18]:
pipe.predict(X)  


array([ 4.95495135e-03, -2.77553225e-02,  3.69509479e-03, -1.33173475e-02,
       -1.07322419e-02, -5.18397864e-02, -2.62834231e-02,  3.86272696e-02,
        7.13601945e-03, -1.30130115e-02, -5.98097614e-02, -4.87315957e-03,
       -1.48189099e-02,  6.16239115e-03, -8.51760901e-03,  3.19136466e-02,
        1.57383528e-02,  2.94368433e-02, -2.53873858e-02, -2.10159471e-02,
       -3.18151715e-02, -2.33380378e-02, -2.29718695e-02,  4.55023173e-02,
       -2.34701457e-02, -1.18886337e-02, -5.39000598e-02, -1.38638642e-02,
       -2.67205855e-02,  1.24185650e-02, -1.50151977e-02, -4.03884229e-02,
        2.06405750e-02, -1.73470330e-02, -4.14075501e-02,  1.85332429e-02,
        5.01600480e-03, -1.65430288e-02,  5.26183537e-02,  3.02657474e-04,
        3.13694636e-02, -5.51624756e-02, -1.94368651e-02, -3.57954358e-03,
        1.69678050e-02, -1.35414972e-03, -3.71529852e-02, -5.78078677e-02,
        1.65562706e-03,  3.13810990e-03, -1.40628247e-02,  2.96302984e-03,
       -3.57248948e-03,  

In [19]:
pipe.score(X, y)

-3.90271854560383

In [20]:

from sklearn.base import ClassifierMixin


class MyOwnClassifier(BaseEstimator, ClassifierMixin):
     def fit(self, X, y):
         self.classes_ = np.unique(y)
         return self
     def predict(self, X):
         return np.random.randint(0, self.classes_.size,
                                  size=X.shape[0])
     def predict_proba(self, X):
         pred = np.random.rand(X.shape[0], self.classes_.size)
         return pred / np.sum(pred, axis=1)[:, np.newaxis]

In [21]:
X, y = load_iris(return_X_y=True)
pipe = make_pipeline(MyOwnTransformer(), MyOwnClassifier())
pipe.fit(X, y)
pipe.predict(X)  

array([1, 2, 1, 2, 1, 0, 1, 2, 1, 1, 1, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 2,
       0, 0, 2, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 0, 1, 0, 0, 0, 1, 2, 0, 0,
       2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 2, 0, 0, 1, 2, 2, 2, 1, 1,
       2, 0, 0, 2, 1, 2, 1, 0, 2, 1, 2, 2, 0, 1, 2, 0, 2, 1, 1, 0, 2, 0,
       2, 1, 1, 0, 2, 1, 1, 1, 2, 0, 1, 2, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 0, 1, 2, 0, 2, 1, 1, 1, 0, 2, 2, 0, 2, 0, 1,
       1, 1, 0, 0, 2, 1, 1, 1, 2, 2, 0, 0, 2, 0, 0, 2, 1, 1])

In [23]:
pipe.predict_proba(X)  




array([[0.25504896, 0.50929901, 0.23565203],
       [0.16610066, 0.12378899, 0.71011034],
       [0.44641436, 0.30312746, 0.25045818],
       [0.36208834, 0.3323963 , 0.30551536],
       [0.45953827, 0.2236072 , 0.31685453],
       [0.4937999 , 0.10710857, 0.39909153],
       [0.30793782, 0.33958886, 0.35247332],
       [0.25734958, 0.6261849 , 0.11646552],
       [0.45032904, 0.13706814, 0.41260282],
       [0.10349343, 0.8726336 , 0.02387297],
       [0.33382898, 0.4304845 , 0.23568652],
       [0.00191718, 0.48323608, 0.51484674],
       [0.14456454, 0.37746283, 0.47797263],
       [0.34373421, 0.34390917, 0.31235662],
       [0.58198562, 0.14553435, 0.27248003],
       [0.3792949 , 0.3122903 , 0.3084148 ],
       [0.50897388, 0.37012965, 0.12089647],
       [0.41423557, 0.28296817, 0.30279626],
       [0.50494587, 0.30899728, 0.18605685],
       [0.01882457, 0.14061339, 0.84056203],
       [0.0365137 , 0.11936275, 0.84412354],
       [0.12389522, 0.6741223 , 0.20198248],
       [0.

In [24]:
pipe.score(X, y)  

0.31333333333333335