<a href="https://colab.research.google.com/github/armandoordonez/eda_couse/blob/main/Basic_Estimators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Carga de librerías
from sklearn.base import TransformerMixin
from sklearn.base import BaseEstimator
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

# Creación clase transformadora

class MyOwnTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X

myot = MyOwnTransformer()

In [14]:
# Carga del dataset

X, y = load_iris(return_X_y=True)

# Aplicamos el transformador
myot.transform(X)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
# Crear pipeline
pipe = make_pipeline(MyOwnTransformer(), LogisticRegression(random_state=10, solver='lbfgs',max_iter=1000))
pipe.fit(X,y)

Pipeline(steps=[('myowntransformer', MyOwnTransformer()),
                ('logisticregression',
                 LogisticRegression(max_iter=1000, random_state=10))])

In [22]:
pipe.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
from sklearn.base import TransformerMixin
from sklearn.base import BaseEstimator
from sklearn.base import RegressorMixin
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

import numpy as np

class MyOwnRegressor(BaseEstimator, RegressorMixin):
    def fit(self, X, y):
        return self
    def predict(self, X):
        return np.mean(X, axis=1)

In [24]:
from sklearn.datasets import load_diabetes


X, y = load_diabetes(return_X_y=True)

pipe = make_pipeline(MyOwnTransformer(), MyOwnRegressor())
pipe.fit(X, y)


Pipeline(steps=[('myowntransformer', MyOwnTransformer()),
                ('myownregressor', MyOwnRegressor())])

In [25]:
pipe.predict(X)


array([ 4.95486093e-03, -2.77554722e-02,  3.69486749e-03, -1.33177387e-02,
       -1.07318583e-02, -5.18393379e-02, -2.62837913e-02,  3.86273006e-02,
        7.13573612e-03, -1.30129042e-02, -5.98101434e-02, -4.87329767e-03,
       -1.48185599e-02,  6.16247009e-03, -8.51720569e-03,  3.19140705e-02,
        1.57380392e-02,  2.94364608e-02, -2.53868917e-02, -2.10158462e-02,
       -3.18147476e-02, -2.33384528e-02, -2.29717691e-02,  4.55032929e-02,
       -2.34701856e-02, -1.18888515e-02, -5.38999041e-02, -1.38638861e-02,
       -2.67207753e-02,  1.24185267e-02, -1.50152087e-02, -4.03884100e-02,
        2.06406733e-02, -1.73465587e-02, -4.14073501e-02,  1.85321833e-02,
        5.01558702e-03, -1.65430865e-02,  5.26187973e-02,  3.02459345e-04,
        3.13692709e-02, -5.51627960e-02, -1.94379695e-02, -3.57936221e-03,
        1.69677258e-02, -1.35447447e-03, -3.71527250e-02, -5.78073618e-02,
        1.65578763e-03,  3.13780528e-03, -1.40629806e-02,  2.96285776e-03,
       -3.57201315e-03,  

In [26]:
pipe.score(X, y)

-3.9027185459647695

In [28]:

from sklearn.base import ClassifierMixin


class MyOwnClassifier(BaseEstimator, ClassifierMixin):
     def fit(self, X, y):
         self.classes_ = np.unique(y)
         return self
     def predict(self, X):
         return np.random.randint(0, self.classes_.size,
                                  size=X.shape[0])
     def predict_proba(self, X):
         pred = np.random.rand(X.shape[0], self.classes_.size)
         return pred / np.sum(pred, axis=1)[:, np.newaxis]

In [29]:
X, y = load_iris(return_X_y=True)
pipe = make_pipeline(MyOwnTransformer(), MyOwnClassifier())
pipe.fit(X, y)
pipe.predict(X)

array([0, 1, 1, 0, 1, 2, 0, 0, 1, 2, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0, 2,
       1, 2, 0, 2, 2, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 2, 1, 1, 1, 0, 2, 2,
       0, 2, 0, 1, 2, 1, 2, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 0, 0, 1, 2, 1, 0, 1, 1,
       1, 2, 1, 1, 2, 0, 1, 1, 2, 2, 1, 2, 0, 2, 0, 1, 0, 2, 2, 0, 0, 1,
       1, 0, 0, 1, 2, 0, 0, 2, 1, 2, 0, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 2, 0, 0, 2, 0, 1, 0, 1, 0, 1, 0, 2, 0])

In [30]:
pipe.predict_proba(X)




array([[0.56216082, 0.36865895, 0.06918023],
       [0.08039793, 0.56975715, 0.34984492],
       [0.13074438, 0.41332748, 0.45592814],
       [0.32680284, 0.01194464, 0.66125252],
       [0.25312819, 0.17407334, 0.57279847],
       [0.13983434, 0.33041254, 0.52975312],
       [0.32194582, 0.39313236, 0.28492182],
       [0.35207682, 0.36554778, 0.2823754 ],
       [0.32289271, 0.13860742, 0.53849987],
       [0.45671121, 0.38043257, 0.16285621],
       [0.47078529, 0.3486206 , 0.18059411],
       [0.54680036, 0.00531717, 0.44788247],
       [0.23551186, 0.52167134, 0.24281681],
       [0.01334667, 0.27372711, 0.71292622],
       [0.02406397, 0.26494126, 0.71099477],
       [0.35815857, 0.34562593, 0.2962155 ],
       [0.31394857, 0.19583057, 0.49022086],
       [0.47049245, 0.18552603, 0.34398152],
       [0.15884087, 0.70182414, 0.13933499],
       [0.13528283, 0.40660191, 0.45811525],
       [0.36889767, 0.38018002, 0.25092231],
       [0.69583779, 0.18538379, 0.11877842],
       [0.

In [31]:
pipe.score(X, y)

0.32666666666666666