<a href="https://colab.research.google.com/github/armandoordonez/eda_couse/blob/main/PCA_con_Imputaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practica de PCA con Imputación

##0. Importar librerias

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

sns.set_theme(style="whitegrid")

## 1. Cargar el dataset

### Usando la libreria de drive

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
df = pd.read_csv('/gdrive/MyDrive/Monitoria IA/Practicas/PCA_Imputacion/diabetes-NAN.csv', na_values = '?')

### Cargando el archivo a google colab

In [ ]:
df = pd.read_csv('./diabetes-NAN.csv', na_values='?')

## 2. Observaciones del dataset

### Tamaño del dataset

In [ ]:
df.shape

(768, 9)

###Información general

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               766 non-null    float64
 1   Glucose                   759 non-null    float64
 2   BloodPressure             761 non-null    float64
 3   SkinThickness             759 non-null    float64
 4   Insulin                   762 non-null    float64
 5   BMI                       761 non-null    float64
 6   DiabetesPedigreeFunction  766 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(7), int64(2)
memory usage: 54.1 KB


###Vista preliminar

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          6.0    148.0           72.0           35.0      0.0  33.6   
1          1.0     85.0           66.0           29.0      0.0  26.6   
2          8.0      NaN           64.0            0.0      0.0  23.3   
3          1.0     89.0           66.0           23.0     94.0  28.1   
4          0.0      NaN            NaN           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763         10.0    101.0           76.0           48.0    180.0  32.9   
764          2.0    122.0           70.0           27.0      0.0  36.8   
765          5.0    121.0           72.0           23.0    112.0  26.2   
766          1.0    126.0           60.0            0.0      0.0  30.1   
767          1.0     93.0           70.0           31.0      0.0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

###Nulos en el dataset

In [ ]:
df.isnull().sum()

Pregnancies                 2
Glucose                     9
BloodPressure               7
SkinThickness               9
Insulin                     6
BMI                         7
DiabetesPedigreeFunction    2
Age                         0
Outcome                     0
dtype: int64

##3. Imputación

La imputación de datos nulos, también conocida como imputación de valores faltantes, es el proceso de estimar o completar los valores que faltan en un conjunto de datos. Los valores faltantes pueden surgir por diversas razones, como errores de entrada, fallos en la recolección de datos, o datos que simplemente no están disponibles.

###Algunos tipos de imputación



*   Imputación por media
*   Imputación por k-vecinos más cercanos
*   Imputación por Interpolación
*   Imputación mediante técnicas de aprendizaje automático





### Imputación por media

In [ ]:
mean_imputer = SimpleImputer(strategy = 'mean')
df_mean_imputed = mean_imputer.fit_transform(df)

In [ ]:
df_mean_imputed = pd.DataFrame(df_mean_imputed)

In [ ]:
df_mean_imputed.rename(columns=dict(zip(df_mean_imputed.columns, df.columns)), inplace=True)


In [ ]:
df_mean_imputed.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### Imputación por k-vecinos más cercanos

In [ ]:
imputer_knn = KNNImputer(n_neighbors=6)
df_knn_imputed = imputer_knn.fit_transform(df)

In [ ]:
df_knn_imputed = pd.DataFrame(df_knn_imputed)

In [ ]:
df_knn_imputed.rename(columns=dict(zip(df_knn_imputed.columns, df.columns)), inplace=True)


In [ ]:
df_knn_imputed.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### Imputación por interpolación

In [ ]:
df_interpolate_imputed = df.interpolate()

In [ ]:
df_interpolate_imputed.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### Imputación mediante técnicas de aprendizaje automático

Imputación mediante técnicas de aprendizaje automático:
Para este caso, cada técnica puede requerir diferentes bibliotecas o enfoques específicos, pero en general, puedes utilizar algoritmos de aprendizaje automático como **RandomForestRegressor**, **SVR** (Support Vector Regression) o **Keras** (para redes neuronales) para implementar la imputación mediante técnicas de aprendizaje automático.

##4.Aplicando PCA a los dataset imputados

In [ ]:
predictores = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
objetivo= 'Outcome'

###Imputación por media

In [ ]:
X_mean = df_mean_imputed[predictores]
y_mean = df_mean_imputed[objetivo]

In [ ]:
pca = PCA(n_components=2)
mean_pca = pca.fit_transform(X_mean)

In [ ]:
mean_pca

array([[-75.89861892, -36.44272662],
       [-82.62181374,  28.45130422],
       [-80.93445067,  -7.59025733],
       ...,
       [ 31.89098115,   3.11947531],
       [-80.40986557, -14.56430567],
       [-81.56253783,  21.17154449]])

### Imputación por knn

In [ ]:
X_knn = df_knn_imputed[predictores]
y_knn = df_knn_imputed[objetivo]

In [ ]:
knn_pca = pca.fit_transform(X_knn)

In [ ]:
knn_pca

array([[-75.78733988, -36.31795106],
       [-82.49340892,  28.54809155],
       [-83.66325662,  20.23066392],
       ...,
       [ 32.00219184,   3.14524962],
       [-80.31870154, -14.52578179],
       [-81.4351513 ,  21.26247887]])

### Imputación por interpolación

In [ ]:
X_interpolate = df_interpolate_imputed[predictores]
y_interpolate = df_interpolate_imputed[objetivo]

In [ ]:
interpolate_pca = pca.fit_transform(X_interpolate)

In [ ]:
interpolate_pca

array([[-77.03185838, -36.56928052],
       [-83.67481437,  28.3585682 ],
       [-85.25381123,  25.11119094],
       ...,
       [ 30.8300548 ,   2.94562143],
       [-81.43242736, -14.50949867],
       [-82.64504285,  21.04629846]])

##5. Predicciones con cada tipo de imputación

In [ ]:
model = LogisticRegression(solver='lbfgs', max_iter=100)

### Media

In [ ]:
X_train_mean, X_test_mean, y_train_mean, y_test_mean = train_test_split(mean_pca, y_mean, test_size=0.2, random_state=42)


In [ ]:
model.fit(X_train_mean, y_train_mean)

LogisticRegression()

In [ ]:
y_pred_mean = model.predict(X_test_mean)

In [ ]:
model.score(X_test_mean, y_test_mean)

0.7272727272727273

### KNN

In [ ]:
X_train_knn, X_test_knn, y_train_knn, y_test_knn = train_test_split(knn_pca, y_knn, test_size=0.2, random_state=42)


In [ ]:
model.fit(X_train_knn, y_train_knn)

LogisticRegression()

In [ ]:
y_pred_knn = model.predict(X_test_knn)

In [ ]:
model.score(X_test_knn, y_test_knn)

0.7272727272727273

### Interpolación

In [ ]:
X_train_interpolate, X_test_interpolate, y_train_interpolate, y_test_interpolate = train_test_split(interpolate_pca, y_interpolate, test_size=0.2, random_state=42)


In [ ]:
model.fit(X_train_interpolate, y_train_interpolate)

LogisticRegression()

In [ ]:
y_pred_interpolate = model.predict(X_test_interpolate)

In [ ]:
model.score(X_test_interpolate, y_test_interpolate)

0.7207792207792207

### Sin ningún tipo de imputación

In [ ]:
df_clean = df.dropna()

In [ ]:
X = df_clean[predictores]
y = df_clean[objetivo]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
model.score(X_test, y_test)

0.8120805369127517

# Conclusiones